{"uuid": "99e45d4a-d6f0-4a46-9e7a-90072dab91ba", "children": ["3b1e00de-618a-483f-8552-9527e3d620b6"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=78.0.3904.97)\n\n", "trace": "  File \"c:\\users\\patelvi\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\patelvi\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\patelvi\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 775, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\patelvi\\PycharmProjects\\NCE\\onx\\test_multi.py\", line 46, in browser\n    driver.get('https://www.kroger.com/')\n  File \"c:\\users\\patelvi\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\patelvi\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\patelvi\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1574177636827, "stop": 1574177639961}], "start": 1574177636827, "stop": 1574177640141}